<?php

use Illuminate\Database\Schema\Blueprint;

/**
 * Created by PhpStorm.
 * User: Armin
 * Date: 21.4.2019.
 * Time: 11:35
 */


class LocationSettingsRefactor
{
    /**
     * Run the database refactoring.
     *
     * @return void
     */
    public function run()
    {
        /*** DODAVANJE KOLONA **/

        if(!Schema::hasTable('location_settings')) {
            Schema::create('location_settings', function (Blueprint $table) {
                $table->engine = 'InnoDB';
                $table->increments('id');
                $table->string('country', 250)->nullable()->default(null);
                $table->string('locale', 50)->nullable()->default(null);
                $table->string('currency', 250)->nullable()->default(null);
                $table->double('exchange_rate', 10, 5)->nullable();
            });

            $countries = [
                ['locale' => 'en', 'country' => "Andorra"],
                ['locale' => 'en', 'country' => "United Arab Emirates"],
                ['locale' => 'en', 'country' => "Afghanistan"],
                ['locale' => 'en', 'country' => "Antigua and Barbuda"],
                ['locale' => 'en', 'country' => "Anguilla"],
                ['locale' => 'en', 'country' => "Albania"],
                ['locale' => 'en', 'country' => "Armenia"],
                ['locale' => 'en', 'country' => "Angola"],
                ['locale' => 'en', 'country' => "Asia/Pacific Region"],
                ['locale' => 'en', 'country' => "Antarctica"],
                ['locale' => 'en', 'country' => "Argentina"],
                ['locale' => 'en', 'country' => "American Samoa"],
                ['locale' => 'en', 'country' => "Austria"],
                ['locale' => 'en', 'country' => "Australia"],
                ['locale' => 'en', 'country' => "Aruba"],
                ['locale' => 'en', 'country' => "Aland Islands"],
                ['locale' => 'en', 'country' => "Azerbaijan"],
                ['locale' => 'sr', 'country' => "Bosnia and Herzegovina"],
                ['locale' => 'en', 'country' => "Barbados"],
                ['locale' => 'en', 'country' => "Bangladesh"],
                ['locale' => 'en', 'country' => "Belgium"],
                ['locale' => 'en', 'country' => "Burkina Faso"],
                ['locale' => 'en', 'country' => "Bulgaria"],
                ['locale' => 'en', 'country' => "Bahrain"],
                ['locale' => 'en', 'country' => "Burundi"],
                ['locale' => 'en', 'country' => "Benin"],
                ['locale' => 'en', 'country' => "Saint Barthelemy"],
                ['locale' => 'en', 'country' => "Bermuda"],
                ['locale' => 'en', 'country' => "Brunei Darussalam"],
                ['locale' => 'en', 'country' => "Bolivia"],
                ['locale' => 'en', 'country' => "Bonaire, Saint Eustatius and Saba"],
                ['locale' => 'en', 'country' => "Brazil"],
                ['locale' => 'en', 'country' => "Bahamas"],
                ['locale' => 'en', 'country' => "Bhutan"],
                ['locale' => 'en', 'country' => "Bouvet Island"],
                ['locale' => 'en', 'country' => "Botswana"],
                ['locale' => 'en', 'country' => "Belarus"],
                ['locale' => 'en', 'country' => "Belize"],
                ['locale' => 'en', 'country' => "Canada"],
                ['locale' => 'en', 'country' => "Cocos (Keeling) Islands"],
                ['locale' => 'en', 'country' => "Congo, The Democratic Republic of the"],
                ['locale' => 'en', 'country' => "Central African Republic"],
                ['locale' => 'en', 'country' => "Congo"],
                ['locale' => 'en', 'country' => "Switzerland"],
                ['locale' => 'en', 'country' => "Cote d'Ivoire"],
                ['locale' => 'en', 'country' => "Cook Islands"],
                ['locale' => 'en', 'country' => "Chile"],
                ['locale' => 'en', 'country' => "Cameroon"],
                ['locale' => 'en', 'country' => "China"],
                ['locale' => 'en', 'country' => "Colombia"],
                ['locale' => 'en', 'country' => "Costa Rica"],
                ['locale' => 'en', 'country' => "Cuba"],
                ['locale' => 'en', 'country' => "Cape Verde"],
                ['locale' => 'en', 'country' => "Curacao"],
                ['locale' => 'en', 'country' => "Christmas Island"],
                ['locale' => 'en', 'country' => "Cyprus"],
                ['locale' => 'en', 'country' => "Czech Republic"],
                ['locale' => 'en', 'country' => "Germany"],
                ['locale' => 'en', 'country' => "Djibouti"],
                ['locale' => 'en', 'country' => "Denmark"],
                ['locale' => 'en', 'country' => "Dominica"],
                ['locale' => 'en', 'country' => "Dominican Republic"],
                ['locale' => 'en', 'country' => "Algeria"],
                ['locale' => 'en', 'country' => "Ecuador"],
                ['locale' => 'en', 'country' => "Estonia"],
                ['locale' => 'en', 'country' => "Egypt"],
                ['locale' => 'en', 'country' => "Western Sahara"],
                ['locale' => 'en', 'country' => "Eritrea"],
                ['locale' => 'en', 'country' => "Spain"],
                ['locale' => 'en', 'country' => "Ethiopia"],
                ['locale' => 'en', 'country' => "Europe"],
                ['locale' => 'en', 'country' => "Finland"],
                ['locale' => 'en', 'country' => "Fiji"],
                ['locale' => 'en', 'country' => "Falkland Islands (Malvinas)"],
                ['locale' => 'en', 'country' => "Micronesia, Federated States of"],
                ['locale' => 'en', 'country' => "Faroe Islands"],
                ['locale' => 'en', 'country' => "France"],
                ['locale' => 'en', 'country' => "Gabon"],
                ['locale' => 'en', 'country' => "United Kingdom"],
                ['locale' => 'en', 'country' => "Grenada"],
                ['locale' => 'en', 'country' => "Georgia"],
                ['locale' => 'en', 'country' => "French Guiana"],
                ['locale' => 'en', 'country' => "Guernsey"],
                ['locale' => 'en', 'country' => "Ghana"],
                ['locale' => 'en', 'country' => "Gibraltar"],
                ['locale' => 'en', 'country' => "Greenland"],
                ['locale' => 'en', 'country' => "Gambia"],
                ['locale' => 'en', 'country' => "Guinea"],
                ['locale' => 'en', 'country' => "Guadeloupe"],
                ['locale' => 'en', 'country' => "Equatorial Guinea"],
                ['locale' => 'en', 'country' => "Greece"],
                ['locale' => 'en', 'country' => "South Georgia and the South Sandwich Islands"],
                ['locale' => 'en', 'country' => "Guatemala"],
                ['locale' => 'en', 'country' => "Guam"],
                ['locale' => 'en', 'country' => "Guinea-Bissau"],
                ['locale' => 'en', 'country' => "Guyana"],
                ['locale' => 'en', 'country' => "Hong Kong"],
                ['locale' => 'en', 'country' => "Heard Island and McDonald Islands"],
                ['locale' => 'en', 'country' => "Honduras"],
                ['locale' => 'sr', 'country' => "Croatia"],
                ['locale' => 'en', 'country' => "Haiti"],
                ['locale' => 'en', 'country' => "Hungary"],
                ['locale' => 'en', 'country' => "Indonesia"],
                ['locale' => 'en', 'country' => "Ireland"],
                ['locale' => 'en', 'country' => "Israel"],
                ['locale' => 'en', 'country' => "Isle of Man"],
                ['locale' => 'en', 'country' => "India"],
                ['locale' => 'en', 'country' => "British Indian Ocean Territory"],
                ['locale' => 'en', 'country' => "Iraq"],
                ['locale' => 'en', 'country' => "Iran, Islamic Republic of"],
                ['locale' => 'en', 'country' => "Iceland"],
                ['locale' => 'en', 'country' => "Italy"],
                ['locale' => 'en', 'country' => "Jersey"],
                ['locale' => 'en', 'country' => "Jamaica"],
                ['locale' => 'en', 'country' => "Jordan"],
                ['locale' => 'en', 'country' => "Japan"],
                ['locale' => 'en', 'country' => "Kenya"],
                ['locale' => 'en', 'country' => "Kyrgyzstan"],
                ['locale' => 'en', 'country' => "Cambodia"],
                ['locale' => 'en', 'country' => "Kiribati"],
                ['locale' => 'en', 'country' => "Comoros"],
                ['locale' => 'en', 'country' => "Saint Kitts and Nevis"],
                ['locale' => 'en', 'country' => "Korea, Democratic People's Republic of"],
                ['locale' => 'en', 'country' => "Korea, Republic of"],
                ['locale' => 'en', 'country' => "Kuwait"],
                ['locale' => 'en', 'country' => "Cayman Islands"],
                ['locale' => 'en', 'country' => "Kazakhstan"],
                ['locale' => 'en', 'country' => "Lao People's Democratic Republic"],
                ['locale' => 'en', 'country' => "Lebanon"],
                ['locale' => 'en', 'country' => "Saint Lucia"],
                ['locale' => 'en', 'country' => "Liechtenstein"],
                ['locale' => 'en', 'country' => "Sri Lanka"],
                ['locale' => 'en', 'country' => "Liberia"],
                ['locale' => 'en', 'country' => "Lesotho"],
                ['locale' => 'en', 'country' => "Lithuania"],
                ['locale' => 'en', 'country' => "Luxembourg"],
                ['locale' => 'en', 'country' => "Latvia"],
                ['locale' => 'en', 'country' => "Libyan Arab Jamahiriya"],
                ['locale' => 'en', 'country' => "Morocco"],
                ['locale' => 'en', 'country' => "Monaco"],
                ['locale' => 'en', 'country' => "Moldova, Republic of"],
                ['locale' => 'sr', 'country' => "Montenegro"],
                ['locale' => 'en', 'country' => "Saint Martin"],
                ['locale' => 'en', 'country' => "Madagascar"],
                ['locale' => 'en', 'country' => "Marshall Islands"],
                ['locale' => 'sr', 'country' => "Macedonia"],
                ['locale' => 'en', 'country' => "Mali"],
                ['locale' => 'en', 'country' => "Myanmar"],
                ['locale' => 'en', 'country' => "Mongolia"],
                ['locale' => 'en', 'country' => "Macao"],
                ['locale' => 'en', 'country' => "Northern Mariana Islands"],
                ['locale' => 'en', 'country' => "Martinique"],
                ['locale' => 'en', 'country' => "Mauritania"],
                ['locale' => 'en', 'country' => "Montserrat"],
                ['locale' => 'en', 'country' => "Malta"],
                ['locale' => 'en', 'country' => "Mauritius"],
                ['locale' => 'en', 'country' => "Maldives"],
                ['locale' => 'en', 'country' => "Malawi"],
                ['locale' => 'en', 'country' => "Mexico"],
                ['locale' => 'en', 'country' => "Malaysia"],
                ['locale' => 'en', 'country' => "Mozambique"],
                ['locale' => 'en', 'country' => "Namibia"],
                ['locale' => 'en', 'country' => "New Caledonia"],
                ['locale' => 'en', 'country' => "Niger"],
                ['locale' => 'en', 'country' => "Norfolk Island"],
                ['locale' => 'en', 'country' => "Nigeria"],
                ['locale' => 'en', 'country' => "Nicaragua"],
                ['locale' => 'en', 'country' => "Netherlands"],
                ['locale' => 'en', 'country' => "Norway"],
                ['locale' => 'en', 'country' => "Nepal"],
                ['locale' => 'en', 'country' => "Nauru"],
                ['locale' => 'en', 'country' => "Niue"],
                ['locale' => 'en', 'country' => "New Zealand"],
                ['locale' => 'en', 'country' => "Oman"],
                ['locale' => 'en', 'country' => "Panama"],
                ['locale' => 'en', 'country' => "Peru"],
                ['locale' => 'en', 'country' => "French Polynesia"],
                ['locale' => 'en', 'country' => "Papua New Guinea"],
                ['locale' => 'en', 'country' => "Philippines"],
                ['locale' => 'en', 'country' => "Pakistan"],
                ['locale' => 'en', 'country' => "Poland"],
                ['locale' => 'en', 'country' => "Saint Pierre and Miquelon"],
                ['locale' => 'en', 'country' => "Pitcairn"],
                ['locale' => 'en', 'country' => "Puerto Rico"],
                ['locale' => 'en', 'country' => "Palestinian Territory"],
                ['locale' => 'en', 'country' => "Portugal"],
                ['locale' => 'en', 'country' => "Palau"],
                ['locale' => 'en', 'country' => "Paraguay"],
                ['locale' => 'en', 'country' => "Qatar"],
                ['locale' => 'en', 'country' => "Reunion"],
                ['locale' => 'en', 'country' => "Romania"],
                ['locale' => 'sr', 'country' => "Serbia"],
                ['locale' => 'en', 'country' => "Russian Federation"],
                ['locale' => 'en', 'country' => "Rwanda"],
                ['locale' => 'en', 'country' => "Saudi Arabia"],
                ['locale' => 'en', 'country' => "Solomon Islands"],
                ['locale' => 'en', 'country' => "Seychelles"],
                ['locale' => 'en', 'country' => "Sudan"],
                ['locale' => 'en', 'country' => "Sweden"],
                ['locale' => 'en', 'country' => "Singapore"],
                ['locale' => 'en', 'country' => "Saint Helena"],
                ['locale' => 'en', 'country' => "Slovenia"],
                ['locale' => 'en', 'country' => "Svalbard and Jan Mayen"],
                ['locale' => 'en', 'country' => "Slovakia"],
                ['locale' => 'en', 'country' => "Sierra Leone"],
                ['locale' => 'en', 'country' => "San Marino"],
                ['locale' => 'en', 'country' => "Senegal"],
                ['locale' => 'en', 'country' => "Somalia"],
                ['locale' => 'en', 'country' => "Suriname"],
                ['locale' => 'en', 'country' => "South Sudan"],
                ['locale' => 'en', 'country' => "Sao Tome and Principe"],
                ['locale' => 'en', 'country' => "El Salvador"],
                ['locale' => 'en', 'country' => "Sint Maarten"],
                ['locale' => 'en', 'country' => "Syrian Arab Republic"],
                ['locale' => 'en', 'country' => "Swaziland"],
                ['locale' => 'en', 'country' => "Turks and Caicos Islands"],
                ['locale' => 'en', 'country' => "Chad"],
                ['locale' => 'en', 'country' => "French Southern Territories"],
                ['locale' => 'en', 'country' => "Togo"],
                ['locale' => 'en', 'country' => "Thailand"],
                ['locale' => 'en', 'country' => "Tajikistan"],
                ['locale' => 'en', 'country' => "Tokelau"],
                ['locale' => 'en', 'country' => "Timor-Leste"],
                ['locale' => 'en', 'country' => "Turkmenistan"],
                ['locale' => 'en', 'country' => "Tunisia"],
                ['locale' => 'en', 'country' => "Tonga"],
                ['locale' => 'en', 'country' => "Turkey"],
                ['locale' => 'en', 'country' => "Trinidad and Tobago"],
                ['locale' => 'en', 'country' => "Tuvalu"],
                ['locale' => 'en', 'country' => "Taiwan"],
                ['locale' => 'en', 'country' => "Tanzania, United Republic of"],
                ['locale' => 'en', 'country' => "Ukraine"],
                ['locale' => 'en', 'country' => "Uganda"],
                ['locale' => 'en', 'country' => "United States Minor Outlying Islands"],
                ['locale' => 'en', 'country' => "United States"],
                ['locale' => 'en', 'country' => "Uruguay"],
                ['locale' => 'en', 'country' => "Uzbekistan"],
                ['locale' => 'en', 'country' => "Holy See (Vatican City State)"],
                ['locale' => 'en', 'country' => "Saint Vincent and the Grenadines"],
                ['locale' => 'en', 'country' => "Venezuela"],
                ['locale' => 'en', 'country' => "Virgin Islands, British"],
                ['locale' => 'en', 'country' => "Virgin Islands, U.S."],
                ['locale' => 'en', 'country' => "Vietnam"],
                ['locale' => 'en', 'country' => "Vanuatu"],
                ['locale' => 'en', 'country' => "Wallis and Futuna"],
                ['locale' => 'en', 'country' => "Samoa"],
                ['locale' => 'en', 'country' => "Yemen"],
                ['locale' => 'en', 'country' => "Mayotte"],
                ['locale' => 'en', 'country' => "South Africa"],
                ['locale' => 'en', 'country' => "Zambia"],
                ['locale' => 'en', 'country' => "Zimbabwe"]
            ];





            foreach ($countries as $key => $country) {
                if($country['country'] == 'Serbia') {
                    $country['currency'] = 'RSD';
                    $country['exchange_rate'] = 0.00846;
                } else if($country['country'] == 'United States') {
                    $country['currency'] = 'USD';
                    $country['exchange_rate'] = 0.88884;
                } else{
                    $country['currency'] = 'EUR';
                    $country['exchange_rate'] = 1;
                }
                $countries[$key] = $country;
            }

            DB::table('location_settings')->insert($countries);
        }

    }
}